# Generated by Django 4.2.6 on 2024-01-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_cotizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('buy_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
